name: complete-devops-project-pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set short SHA
        run: echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t complete-devops-project:$SHORT_SHA .
          docker tag complete-devops-project:$SHORT_SHA thiexco/complete-devops-project:$SHORT_SHA

      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_TOKEN }}
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
        
      - name: Push Docker image
        run: |
          docker push thiexco/complete-devops-project:$SHORT_SHA

      - name: Configure Git Author
        run: |
          git config --global user.name "newthiesco"
          git config --global user.email "newthiesco@gmail.com"

      - name: Update Helm Chart with new image tag
        run: |
          sed -i "s/tag: .*/tag: $SHORT_SHA/" ./complete-devops-project/values.yaml

          # helm upgrade --install complete-devops-project ./helm/complete-devops-project \
          #   --set image.repository=thiexco/complete-devops-project \
          #   --set image.tag=$SHORT_SHA \
          #   --namespace complete-devops-project \
          #   --create-namespace

